---
# handlers file for hardening
- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: reload sysctl
  shell: sysctl -p

- name: restart firewall
  service:
    name: firewalld
    state: restarted