---
# tasks file for hardening
- name: hardening role | setting up umask for the server
  shell: umask
  register: umask_output

- name:  hardening role | displaying umask output
  debug:
    var: umask_output.stdout_lines

- name: hardening role | creating a directory
  file:
   path: /usr/local/test
   state: directory

- name: hardening role | checking the directory permmissions
  stat:
    path: /usr/local/test
  register: permissions

- name: hardening role | Display directory permissions
  debug:
    msg: "Directory permissions of /usr/local/test are {{ permissions.stat.mode }}"
  when: permissions.stat.exists

- name: hardening role | removing the test directory
  file:
   path: /usr/local/test
   state: absent
  when: permissions.stat.exists

- name: hardening role | securing sshd config file | enforcing strict mode
  shell: sed -i 's/#StrictModes yes/StrictModes yes/g' /etc/ssh/sshd_config

- name: hardening role | securing sshd config file | enforcing PAM authentication | step 1
  lineinfile:
    path: /etc/ssh/sshd_config
    line: '#UsePAM no'
    state: absent

- name: hardening role | securing sshd config file | enforcing PAM authentication | step 2
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'UsePAM yes'
    insertafter: EOF
    state: present
  notify: Restart sshd

- name: hardening role | denying cron for all users |
  shell: echo ALL >> /etc/cron.deny

- name: hardening role | turning off ipv6
  lineinfile:
    path: /etc/sysctl.d/60-gce-network-security.conf
    line:
      - 'net.ipv6.conf.all.disable_ipv6 = 1'
      - 'net.ipv6.conf.default.disable_ipv6 = 1'
    insertafter: EOF
    state: present
  notify: reload sysctl