---
# tasks file for filesystem
- name: Filesystem creation | collecting system informations
  setup:
    gather_subset:
      - hardware

- name: Filter and display devices
  debug:
    msg: "{{ ansible_devices | dict2items | selectattr('value.partitions', 'defined') | map(attribute='key') | list }}"