---
vars:
  url: "https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.7.4-el9.aarch64.rpm"
  package: "/usr/loca/nessus.rpm"
# tasks file for nessus
- name: vulnerability assessment | Nessus scan | Downloading nessus
  get_url:
    url: "{{ url }}"
    dest: "{{ package }}"
    mode: 644
  