---
# tasks file for nessus
- name: vulnerability assessment | Nessus scan | Downloading Nessus
  get_url:
    url: "{{ url }}"
    dest: "{{ package }}"
    mode: 644
- name: vulnerability assessment | Nessus scan | Installing dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - 'glibc'
- name:  vulnerability assessment | Nessus scan | key installation 
  shell:
    cmd: rpm --import /usr/local/tenable.gpg

- name: vulnerability assessment | Nessus scan | Installing Nessus
  yum:
    name: "{{ package }}"
    state: present
    update_cache: yes

- name: vulnerability assessment | Nessus scan | starting Nessus service
  systemd:
    name: nessusd
    state: started
    enabled: yes