---
- name: zabbbix monitoring role | installation steps | install zabbix and its dependent packages
  dnf:
    name:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-selinux-policy
      - zabbix-agent
    state: present
    enablerepo: epel
