---
- name: zabbbix monitoring role | Mysql configuration | mysql server status check
  shell:
    cmd: "rpm -qa | grep zabbix-server-mysql"
  register: mysql_status
  ignore_errors: yes

- name: zabbbix monitoring role | Mysql configuration | zabbix mysql server status display
  debug:
    msg: " Zabbix mysql is {{ 'installed' if mysql_status.rc == 0 else 'not installed' }}"

- name: zabbbix monitoring role | Mysql configuration | Installing mysql server 
  dnf:
    name: mysql-server
    state: present

- name: zabbbix monitoring role | Mysql configuration | starting mysql server
  service:
    name: mysqld
    state: started
    enabled: yes
- name: zabbbix monitoring role | Mysql configuration | creating zabbix db
  community.mysql.mysql_db:
    name: zabbix
    state: present

- name: zabbbix monitoring role | Mysql configuration | creating zabbix user
  community.mysql.mysql_user:
    name: zabbix
    password: admin@123
    priv: '*.*:ALL'
    state: present


