---
- name: zabbbix monitoring role | checking epel repo
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: repo_output

- name: zabbix monitoring role | installing epel repo
  yum:
    name: epel-release
    state: present
  when: not repo_output.stat.exists
