---
- name: zabbix monitoring role | pre-installation steps | disable module filtering
  shell:
    cmd: dnf module disable mariadb

- name: zabbix monitoring role | pre-installation steps | Install mariadb development libraries
  yum:
    name: mariadb-devel
    state: present
    disable_gpg_check: yes

- name: zabbix monitoring role | pre-installation steps | installing python packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-devel
    - python3-pip
    - gcc
    - openssl-devel
    - libffi-devel

- name: zabbix monitoring role | pre-installation steps | installing pip
  pip:
    name: pip
    executable: pip3
    state: present

- name: zabbix monitoring role | pre-installation steps | installing pymysql
  pip:
    name: mysqlclient
    executable: pip3
    state: present