---
- name: vm server hardening
  hosts: localhost
  vars:
    include_openvas: true
  tasks:
    - name: calling  hardening role
      include_role:
        name: hardening
      when: include_hardening | default(false)

    - name: zabbix role
      include_role:
        name: zabbix
      when: include_zabbix | default(false)
