---
- name: vm server hardening
  hosts: localhost
  include_hardening: true
  tasks:
    - name: calling  hardening role
      include_role:
        name: hardening
      when: include_hardening is defined